MAIN="python src/main.py"
GRAPH="$1"
LABELS="$2"
WALK="$3"
MODEL="$4"
ENCODE_ARGS="$5 -g $GRAPH -o $LABELS"
WALK_ARGS="$6 -g $GRAPH -m $LABELS -o $WALK"
EMBED_ARGS="$7 -w $WALK -o $MODEL"
GLOBAL_ARGS="$8"

$MAIN $GLOBAL_ARGS encode $ENCODE_ARGS 
$MAIN $GLOBAL_ARGS walk $WALK_ARGS
$MAIN $GLOBAL_ARGS embed $EMBED_ARGS
